// <auto-generated />
namespace ATM_WebSite_Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ATM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ATM));
        
        string IMigrationMetadata.Id
        {
            get { return "202108140946228_ATM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
